version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: inventory-mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: inventory_db
      MYSQL_ROOT_PASSWORD: admin
    restart: always